### PR TITLE
Fix building with gcc/mingw32

### PR DESCRIPTION
**Pull request by Cwiiis**
This fixes building under MSYS/Windows for me.

### CODE REVIEW

**Comment by Cwiiis** [comment]
Note that although this gets it building, it doesn't necessarily work... When executing, I see it flash a window up, but it quits with the error message:

```
Graphics::initialise() : failed to create SDL font _surface
```

**Comment by at67** [comment]
Hmm some interesting changes, the perplexing one is the undef of main, your code should not link if you have main undefined, as SDL2 uses the main redefinition to point to it's own initialisation and WinMain, (note I don't agree with what SDL2 does, just pointing out what it does :))
http://wiki.libsdl.org/FAQWindows#I_get_.22Undefined_reference_to_.27SDL_main.27.22_...

This error message "Graphics::initialise() : failed to create SDL font _surface" most likely means you are missing the file "EmuFont-96x48.bmp", it needs to be where the exe is or in the PATH etc. A better error message is probably a good idea here :)

The _X is hilarious, are you telling me that one of the Windows includes has actually defined _X? If so, that is probably the dumbest thing I have heard of in a long time...a two character define in a major include file, of a major development system, for a major operating system, used by millions, hilarious! 

I don't get any of the build issues that you do, which compiler are you using? I have multiple here I can try the code with, I'd like it to compile with everything obviously.

**Comment by Cwiiis** [comment]
I'm using gcc 7.3.0 via MSYS2 (http://www.msys2.org/) - I was using the pre-built libSDL2, perhaps that isn't compatible with MSYS2 so that could explain the #undef main thing - I'll try building libSDL2 from source to see if it resolves that issue.

I'm not sure where _X is being defined, but there are many similar defines in the Linux X11 headers that often trip things up I've found - it's certainly not a problem unique to Windows :) Are you building successfully for Windows? (And Linux?) What setup/compiler/distro are you using?

**Comment by Cwiiis** [comment]
I'm going to blame CMake - running in Mingw mode and building manually with:

```
g++ -o gtemuSDL *.cpp `sdl2-config --cflags --libs`
```

works fine without the need for undefining main. I've removed that change from this PR and retitled the commit more accurately. CMake seems to just go kinda nuts under msys/mingw32... It does complain that it doesn't recognise the platform though, so I guess it really doesn't support it :)

**Comment by at67** [comment]
I'm assuming it runs for you now?

**Comment by Cwiiis** [comment]
It does, yes, now just need to figure out how to un-fullscreen it so I can read the instructions while using it :) (feature-request: on-screen controls legend, either permanently visible, visible by context, or visible when you press '?' and/or 'h')

**Comment by at67** [comment]
Hmmm, mine is in windowed mode, I forced it into windowed mode by setting the horizontal resolution one pixel wider than the desktop resolution, (old windows trick). 

Go to graphics.cpp:56 and set the width and height in SDL_CreateWindowAndRenderer() to your preference.

I've been meaning to add a help bar across the bottom that toggles when you hit 'h' for weeks, I'll do it now, (but first dinner).

P.S. I just uploaded a working GCL example to play back MIDI, you may be interested if you haven't finished it yourself yet.

**Comment by Cwiiis** [comment]
Cool, I'll check it out :) While I'm feature-requesting, it'd be good to be able to move up from the directory you execute the emulator in (or maybe you already can and I've just not figured out how yet) - I usually build in a subdirectory of the project but I'd like to be able to navigate to all the examples.

**Comment by Cwiiis** [comment]
A thought, I wonder if your technique of starting windowed doesn't work with extended desktops? (I'm running two monitors, or rather, a laptop screen and a monitor)

**Comment by at67** [comment]
I was putting off doing the full directory/drive navigating thing, I'll add directory handling now, but drive navigating can wait.

I'm running 3 monitors here, no issues at all.

**Comment by Cwiiis** [comment]
Gonna abuse Github comments again - was just wondering, is there a reason the binary doesn't try to read EmuFont from the image directory? Or conversely, why the font isn't just in the src directory? Currently, it expects a vCPU directory to exist for code which exists in the srcdir, so I guess it kind of expects to be run from the srcdir?

Ideally the font would be compiled into the binary so it could run standalone (and then perhaps the root dir would just be the current dir too, and perhaps allow navigating to '..' so you could load from any relative directory).

I'm just thinking of things that would make it easier/more understandable from a new user perspective - it'd be great if you could just drop the binary in a directory of .gt1/.vasm files and run it.

**Comment by at67** [comment]
Yup, some good ideas, working on them now.

**Pull request merged**
